### PR TITLE
Misc fixes needed to start C;C

### PR DESCRIPTION
**Pull request by casept**
Misc. issues I noticed and fixed while trying to run Chaos;Child. See commit messages for details.

Video playback is still broken due to a deeper issue; I haven't investigated this yet. At least it doesn't crash when attempting playback anymore.

### CODE REVIEW

**Comment by MrRevo3D** [comment]
@casept Hello. Could you please provide some details on the video playback situation? Which videos are you using? Is it failing to open the stream or failing the ffmpeg part? How is your directory structure set up, etc.? Videos and C;C in general work completely fine on Windows at least, I guess that's why none of this was noticed, I primarly do development on Windows for this.

**Review by MrRevo3D — APPROVED** [review]

**Comment by casept** [comment]
I think it's trying to play the OP or something else very early in the game, as the crash happens before the title menu is visible.

It's failing to open the stream, with the error suggesting that it can't find the file in VFS. This then causes a NULL stream to be created, which is passed along to the ffmpeg functions due to missing error checks.

I'm using the Steam version of the game on Linux. I think my version of the game is different than the one you're testing against, as the game scripts are contained in `script.mpk` instead of `script.cls`. I've edited this path in my local `profiles/cc/vfs.lua`, but haven't committed it because I don't want to break whatever version you seem to be using.

The directory structure of the game data is like so:

```
$ tree .
.
├── bink2w32.dll
├── boot.bat
├── font-lb
│   ├── foreground.png
│   ├── outline.png
│   └── widths.bin
├── gamedata
│   ├── bg1.mpk
│   ├── bg2.mpk
│   ├── bgeffect.mpk
│   ├── bgm.mpk
│   ├── chara.mpk
│   ├── manual.mpk
│   ├── mask.mpk
│   ├── mgsshader.mpk
│   ├── movie
│   │   ├── 1280x720
│   │   │   ├── cc_ed001a.bk2
│   │   │   ├── cc_ed002a.bk2
│   │   │   ├── CC_INT000.bk2
│   │   │   ├── cc_mov001a.bk2
│   │   │   ├── cc_mov002a.bk2
│   │   │   ├── cc_mov003a.bk2
│   │   │   ├── cc_mov004a.bk2
│   │   │   ├── cc_mov005a.bk2
│   │   │   ├── cc_mov005a_en.bk2
│   │   │   ├── cc_mov006a.bk2
│   │   │   ├── cc_mov009a.bk2
│   │   │   ├── cc_mov010a.bk2
│   │   │   ├── cc_mov011a.bk2
│   │   │   ├── cc_mov012a.bk2
│   │   │   ├── cc_mov013a.bk2
│   │   │   ├── cc_mov014a.bk2
│   │   │   ├── cc_mov015a.bk2
│   │   │   ├── cc_mov016a.bk2
│   │   │   ├── cc_mov017a.bk2
│   │   │   ├── cc_mov018a.bk2
│   │   │   ├── cc_mov019a.bk2
│   │   │   ├── cc_mov020a.bk2
│   │   │   ├── cc_TTL000a.bk2
│   │   │   ├── cc_ttl001a.bk2
│   │   │   ├── cc_ttl002a.bk2
│   │   │   ├── cc_ttl003a.bk2
│   │   │   ├── cc_ttl004a.bk2
│   │   │   ├── cc_ttl005a.bk2
│   │   │   ├── cc_ttl006a.bk2
│   │   │   ├── cc_ttl007a.bk2
│   │   │   ├── cc_ttl008a.bk2
│   │   │   ├── cc_ttl009a.bk2
│   │   │   ├── cc_ttl010a.bk2
│   │   │   ├── cc_ttl011a.bk2
│   │   │   ├── cc_ttl012a.bk2
│   │   │   ├── cc_ttl013a.bk2
│   │   │   ├── cc_ttl014a.bk2
│   │   │   ├── cc_ttl015a.bk2
│   │   │   ├── cc_ttl016a.bk2
│   │   │   ├── DISEFF_001A.bk2
│   │   │   ├── DISEFF_001A_en.bk2
│   │   │   ├── DISEFF_001B.bk2
│   │   │   ├── DISEFF_001C.bk2
│   │   │   ├── DISEFF_002A.bk2
│   │   │   ├── DISEFF_002B.bk2
│   │   │   ├── DISEFF_002C.bk2
│   │   │   ├── DISEFF_002D.bk2
│   │   │   ├── DISEFF_002E.bk2
│   │   │   ├── DISEFF_002F.bk2
│   │   │   ├── DISEFF_002G.bk2
│   │   │   ├── DISEFF_002H.bk2
│   │   │   ├── DISEFF_002I.bk2
│   │   │   ├── DISEFF_002J.bk2
│   │   │   ├── DISEFF_002K.bk2
│   │   │   ├── DISEFF_002L.bk2
│   │   │   ├── DISEFF_002M.bk2
│   │   │   ├── DISEFF_002N.bk2
│   │   │   ├── DISEFF_002O.bk2
│   │   │   ├── DISEFF_002P.bk2
│   │   │   ├── DISEFF_002Q.bk2
│   │   │   ├── DISEFF_002R.bk2
│   │   │   ├── DISEFF_003A.bk2
│   │   │   ├── DISEFF_003B.bk2
│   │   │   ├── DISEFF_003C.bk2
│   │   │   ├── DISEFF_003D.bk2
│   │   │   ├── DISEFF_003E.bk2
│   │   │   ├── DISEFF_003F.bk2
│   │   │   ├── DISEFF_003G.bk2
│   │   │   ├── DISEFF_003H.bk2
│   │   │   ├── DISEFF_003I.bk2
│   │   │   ├── DISEFF_003J.bk2
│   │   │   ├── DISEFF_003K.bk2
│   │   │   ├── DISEFF_003L.bk2
│   │   │   ├── DISEFF_003M.bk2
│   │   │   ├── DISEFF_003N.bk2
│   │   │   ├── DISEFF_003O.bk2
│   │   │   ├── DISEFF_003P.bk2
│   │   │   ├── DISEFF_003Q.bk2
│   │   │   ├── DISEFF_003R.bk2
│   │   │   ├── DISEFF_004A.bk2
│   │   │   ├── DISEFF_005A.bk2
│   │   │   ├── movie_op2.bk2
│   │   │   ├── movie_op.bk2
│   │   │   ├── trigger_more.bk2
│   │   │   ├── trigger_negative.bk2
│   │   │   ├── trigger_out.bk2
│   │   │   ├── trigger_positive.bk2
│   │   │   ├── trigger_wait.bk2
│   │   │   └── trigger_wait_short.bk2
│   │   └── 1920x1080
│   │       ├── cc_ed001a.bk2
│   │       ├── cc_ed002a.bk2
│   │       ├── CC_INT000.bk2
│   │       ├── cc_mov001a.bk2
│   │       ├── cc_mov002a.bk2
│   │       ├── cc_mov003a.bk2
│   │       ├── cc_mov004a.bk2
│   │       ├── cc_mov005a.bk2
│   │       ├── cc_mov006a.bk2
│   │       ├── cc_mov009a.bk2
│   │       ├── cc_mov010a.bk2
│   │       ├── cc_mov011a.bk2
│   │       ├── cc_mov012a.bk2
│   │       ├── cc_mov013a.bk2
│   │       ├── cc_mov014a.bk2
│   │       ├── cc_mov015a.bk2
│   │       ├── cc_mov016a.bk2
│   │       ├── cc_mov017a.bk2
│   │       ├── cc_mov018a.bk2
│   │       ├── cc_mov019a.bk2
│   │       ├── cc_mov020a.bk2
│   │       ├── cc_TTL000a.bk2
│   │       ├── cc_TTL001a.bk2
│   │       ├── cc_TTL002a.bk2
│   │       ├── cc_TTL003a.bk2
│   │       ├── cc_TTL004a.bk2
│   │       ├── cc_TTL005a.bk2
│   │       ├── cc_TTL006a.bk2
│   │       ├── cc_TTL007a.bk2
│   │       ├── cc_TTL008a.bk2
│   │       ├── cc_TTL009a.bk2
│   │       ├── cc_TTL010a.bk2
│   │       ├── cc_TTL011a.bk2
│   │       ├── cc_TTL012a.bk2
│   │       ├── cc_TTL013a.bk2
│   │       ├── cc_TTL014a.bk2
│   │       ├── cc_TTL015a.bk2
│   │       ├── cc_TTL016a.bk2
│   │       ├── DISEFF_001A.bk2
│   │       ├── DISEFF_001B.bk2
│   │       ├── DISEFF_001C.bk2
│   │       ├── DISEFF_002A.bk2
│   │       ├── DISEFF_002B.bk2
│   │       ├── DISEFF_002C.bk2
│   │       ├── DISEFF_002D.bk2
│   │       ├── DISEFF_002E.bk2
│   │       ├── DISEFF_002F.bk2
│   │       ├── DISEFF_002G.bk2
│   │       ├── DISEFF_002H.bk2
│   │       ├── DISEFF_002I.bk2
│   │       ├── DISEFF_002J.bk2
│   │       ├── DISEFF_002K.bk2
│   │       ├── DISEFF_002L.bk2
│   │       ├── DISEFF_002M.bk2
│   │       ├── DISEFF_002N.bk2
│   │       ├── DISEFF_002O.bk2
│   │       ├── DISEFF_002P.bk2
│   │       ├── DISEFF_002Q.bk2
│   │       ├── DISEFF_002R.bk2
│   │       ├── DISEFF_003A.bk2
│   │       ├── DISEFF_003B.bk2
│   │       ├── DISEFF_003C.bk2
│   │       ├── DISEFF_003D.bk2
│   │       ├── DISEFF_003E.bk2
│   │       ├── DISEFF_003F.bk2
│   │       ├── DISEFF_003G.bk2
│   │       ├── DISEFF_003H.bk2
│   │       ├── DISEFF_003I.bk2
│   │       ├── DISEFF_003J.bk2
│   │       ├── DISEFF_003K.bk2
│   │       ├── DISEFF_003L.bk2
│   │       ├── DISEFF_003M.bk2
│   │       ├── DISEFF_003N.bk2
│   │       ├── DISEFF_003O.bk2
│   │       ├── DISEFF_003P.bk2
│   │       ├── DISEFF_003Q.bk2
│   │       ├── DISEFF_003R.bk2
│   │       ├── DISEFF_004A.bk2
│   │       ├── DISEFF_005A.bk2
│   │       ├── movie_op2.bk2
│   │       ├── movie_op.bk2
│   │       ├── trigger_more.bk2
│   │       ├── trigger_negative.bk2
│   │       ├── trigger_out.bk2
│   │       ├── trigger_positive.bk2
│   │       ├── trigger_wait.bk2
│   │       └── trigger_wait_short.bk2
│   ├── script.mpk
│   ├── se.mpk
│   ├── shader.mpk
│   ├── sysse.mpk
│   ├── system.mpk
│   └── voice.mpk
├── Game.exe
├── launcher.dat
├── launcher.exe
└── steam_api.dll
```

**Comment by MrRevo3D** [comment]
@casept Ah, okay, I see. First of all there is no support for Bink2 videos since those are not supported by FFmpeg. And second unfortunately it won't work just like that either. You need to have a movie archive. In the original Steam version this is hardcoded in the exe, but in impacto we need to use a cls archive (which is basically just a text file with all file names in order of IDs and a folder with the same name with all the files). For example this is the contents of my movie.cls
```
cc_ed001a.mp4
cc_ed002a.mp4
cc_int000.mp4
cc_mov001a.mp4
cc_mov002a.mp4
cc_mov003a.mp4
cc_mov004a.mp4
cc_mov005a.mp4
cc_mov006a.mp4
cc_mov009a.mp4
cc_mov010a.mp4
cc_mov011a.mp4
cc_mov012a.mp4
cc_mov013a.mp4
cc_mov014a.mp4
cc_mov015a.mp4
cc_mov016a.mp4
cc_mov017a.mp4
cc_mov018a.mp4
cc_mov019a.mp4
cc_mov020a.mp4
cc_ttl000a.mp4
cc_ttl001a.mp4
cc_ttl002a.mp4
cc_ttl003a.mp4
cc_ttl004a.mp4
cc_ttl005a.mp4
cc_ttl006a.mp4
cc_ttl007a.mp4
cc_ttl008a.mp4
cc_ttl009a.mp4
cc_ttl010a.mp4
cc_ttl011a.mp4
cc_ttl012a.mp4
cc_ttl013a.mp4
cc_ttl014a.mp4
cc_ttl015a.mp4
cc_ttl016a.mp4
diseff_001a.mp4
diseff_001b.mp4
diseff_001c.mp4
diseff_002a.mp4
diseff_002b.mp4
diseff_002c.mp4
diseff_002d.mp4
diseff_002e.mp4
diseff_002f.mp4
diseff_002g.mp4
diseff_002h.mp4
diseff_002i.mp4
diseff_002j.mp4
diseff_002k.mp4
diseff_002l.mp4
diseff_002m.mp4
diseff_002n.mp4
diseff_002o.mp4
diseff_002p.mp4
diseff_002q.mp4
diseff_002r.mp4
diseff_003a.mp4
diseff_003b.mp4
diseff_003c.mp4
diseff_003d.mp4
diseff_003e.mp4
diseff_003f.mp4
diseff_003g.mp4
diseff_003h.mp4
diseff_003i.mp4
diseff_003j.mp4
diseff_003k.mp4
diseff_003l.mp4
diseff_003m.mp4
diseff_003n.mp4
diseff_003o.mp4
diseff_003p.mp4
diseff_003q.mp4
diseff_003r.mp4
diseff_004a.mp4
diseff_005a.mp4
movie_op.mp4
rain_effect.mp4
trigger_more.mp4
trigger_negative.mp4
trigger_out.mp4
trigger_positive.mp4
trigger_wait.mp4
trigger_wait_short.mp4
movie_op2.mp4
```
and the tree of gamedata folder
```
│   bg.mpk
│   bgm.mpk
│   chara.mpk
│   mask.mpk
│   movie.cls
│   script.mpk
│   se.mpk
│   shader.mpk
│   sysse.mpk
│   system.mpk
│   voice.mpk
│
├───movie
│       cc_ed001a.mp4
│       cc_ed002a.mp4
│       cc_int000.mp4
│       etc.....
```

**Comment by MrRevo3D** [comment]
With the Steam version you can probably convert all the bk2 files to something that ffmpeg plays and create a similar structure with having all videos in the movie folder and movie.cls.

**Pull request merged**
